-- 코드를 입력하세요
SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE
, PRODUCT_ID AS PRODUCT_ID
, USER_ID AS USER_ID
, SALES_AMOUNT AS SALELS_AMOUNT
FROM ONLINE_SALE
WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-03'
UNION
SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD')
, PRODUCT_ID
, NULL
, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-03'
ORDER BY 1, 2, 3;