-- 코드를 입력하세요
SELECT A.FLAVOR
FROM (
    SELECT H.FLAVOR
FROM FIRST_HALF H, (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) J
WHERE H.FLAVOR = J.FLAVOR
ORDER BY (H.TOTAL_ORDER + J.TOTAL_ORDER) DESC
) A
WHERE ROWNUM <= 3